# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Trivy

on:
  push:
  # schedule:
  #   - cron: '20 4 * * 1'
  # workflow_dispatch:
  
jobs:
  trivy:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          fetch-depth: 0

      - name: Run Trivy vulnerability scanner in IaC mode
        # uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5 #tag=0.8.0
        uses: aquasecurity/trivy-action@0.12.0
        with:
          scan-type: 'config'
          format: 'sarif'
          output: 'trivy-results.sarif'
  
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@312e093a1892bd801f026f1090904ee8e460b9b6 # v2.1.34
        with:
          sarif_file: 'trivy-results.sarif'